### ISSUE TITLE
Feature request: Flag to enable RAG

### ISSUE THREAD

**Issue by leseb** [llamastack/llama-stack-k8s-operator#12]
By [cooktheryan](https://github.com/cooktheryan) in https://github.com/opendatahub-io/llama-stack-k8s-operator/issues/18

The operator should have the ability to optionally deploy Milvus-lite as the vectorDB. This can be accomplished by adding the following to the llama stack run config

```
  vector_io:
  - provider_id: milvus
    provider_type: inline::milvus
    config:
     db_path: ${env.MILVUS_DB_PATH}
```

The DB path we could either make an optional path or hardcode something that we can attach a pvc to
