### ISSUE TITLE
Feature request: Allow for multiple inference servers to be defined

### ISSUE THREAD

**Issue by leseb** [llamastack/llama-stack-k8s-operator#13]
By [cooktheryan](https://github.com/cooktheryan) in https://github.com/opendatahub-io/llama-stack-k8s-operator/issues/17

There may be a need for Llama stack to have multiple inference servers. This could be granite and llama guard or etc. We shouldn't limit the amount of models we allow for a user to define. This allows for folks to dictate the best model for their usage but all of it maintained through the namespaced llama stack instance. 

Below is an example of our configmap and deployment used for developing MCP servers and etc.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamastack-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: llamastack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: llamastack
    spec:
      containers:
      - args:
        - --config
        - /app-config/config.yaml
        env:
        - name: MAX_TOKENS
          value: "128000"
        - name: VLLM_MAX_TOKENS
          value: "128000"
        - name: LLAMA3B_MODEL
          value: meta-llama/Llama-3.2-3B-Instruct
        - name: GRANITE_URL
          value: https://granite-8b-llama-serve.apps.ocp-beta-test.nerc.mghpcc.org/v1
        - name: GRANITE_MODEL
          value: ibm-granite/granite-3.2-8b-instruct
        - name: LLAMA3B_URL
          value: https://llama32-3b-llama-serve.apps.ocp-beta-test.nerc.mghpcc.org/v1
        - name: VLLM_API_TOKEN
          value: fake
        - name: LLAMA_STACK_LOG
          value: debug
        - name: OTEL_SERVICE_NAME
          value: om-llamastack
        - name: OTEL_TRACE_ENDPOINT
          value: http://otel-collector-collector.observability-hub.svc.cluster.local:4318/v1/traces
        - name: SAFETY_MODEL
          value: meta-llama/Llama-Guard-3-8B
        - name: SAFETY_VLLM_URL
          value: http://safety.llama-serve.svc.cluster.local:8000/v1
        - name: MILVUS_DB_PATH
          value: milvus.db
        - name: LLAMA70B_MODEL
          value: meta-llama/Llama-3.3-70B-Instruct
        - name: LLAMA70B_URL
          value: https://llama33-70b-llama-serve.apps.ocp-beta-test.nerc.mghpcc.org/v1
        image: quay.io/redhat-et/llama:vllm-0.1.9
        imagePullPolicy: Always
        name: llamastack
        ports:
        - containerPort: 8321
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /pythainlp-data
          name: pythain
        - mountPath: /app-config
          name: run-config-volume
        - mountPath: /.llama
          name: llama-persist
        - mountPath: /.cache
          name: cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: run-config
        name: run-config-volume
      - name: llama-persist
        persistentVolumeClaim:
          claimName: llama-persist
      - emptyDir: {}
        name: cache
      - emptyDir: {}
        name: pythain
```

Configmap
```
version: '2'
image_name: remote-vllm
apis:
- agents
- datasetio
- eval
- inference
- safety
- scoring
- telemetry
- tool_runtime
- vector_io
providers:
  inference:
  - provider_id: llama-70b
    provider_type: remote::vllm
    config:
      url: ${env.LLAMA70B_URL}
      max_tokens: 128000
      api_token: fake
      tls_verify: false
  - provider_id: llama-3b
    provider_type: remote::vllm
    config:
      url: ${env.LLAMA3B_URL}
      max_tokens: 128000
      api_token: fake
      tls_verify: false
  - provider_id: granite
    provider_type: remote::vllm
    config:
      url: ${env.GRANITE_URL}
      max_tokens: 128000
      api_token: fake
      tls_verify: false
  - provider_id: vllm-safety
    provider_type: remote::vllm
    config:
      url: ${env.SAFETY_VLLM_URL}
      max_tokens: 4096
      api_token: fake
      tls_verify: false
  - provider_id: sentence-transformers
    provider_type: inline::sentence-transformers
    config: {}
  vector_io:
  - provider_id: milvus
    provider_type: inline::milvus
    config:
     db_path: ${env.MILVUS_DB_PATH}
  safety:
  - provider_id: llama-guard
    provider_type: inline::llama-guard
    config:
      excluded_categories: []
  agents:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      persistence_store:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/remote-vllm}/agents_store.db
  eval:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/remote-vllm}/meta_reference_eval.db
  datasetio:
  - provider_id: huggingface
    provider_type: remote::huggingface
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/remote-vllm}/huggingface_datasetio.db
  - provider_id: localfs
    provider_type: inline::localfs
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/remote-vllm}/localfs_datasetio.db
  scoring:
  - provider_id: basic
    provider_type: inline::basic
    config: {}
  - provider_id: llm-as-judge
    provider_type: inline::llm-as-judge
    config: {}
  - provider_id: braintrust
    provider_type: inline::braintrust
    config:
      openai_api_key: ${env.OPENAI_API_KEY:}
  telemetry:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      service_name: ${env.OTEL_SERVICE_NAME:llama-stack}
      sinks: ${env.TELEMETRY_SINKS:console, otel_trace, sqlite}
      otel_trace_endpoint: ${env.OTEL_TRACE_ENDPOINT:}
      sqlite_db_path: ${env.SQLITE_DB_PATH:~/.llama/distributions/remote-vllm/trace_store.db}
  tool_runtime:
  - provider_id: brave-search
    provider_type: remote::brave-search
    config:
      api_key: ${env.BRAVE_SEARCH_API_KEY:}
      max_results: 3
  - provider_id: tavily-search
    provider_type: remote::tavily-search
    config:
      api_key: ${env.TAVILY_SEARCH_API_KEY:}
      max_results: 3
  - provider_id: code-interpreter
    provider_type: inline::code-interpreter
    config: {}
  - provider_id: rag-runtime
    provider_type: inline::rag-runtime
    config: {}
  - provider_id: model-context-protocol
    provider_type: remote::model-context-protocol
    config: {}
metadata_store:
  type: sqlite
  db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/remote-vllm}/registry.db
models:
- metadata: {}
  model_id: ${env.LLAMA70B_MODEL}
  provider_id: llama-70b
  model_type: llm
- metadata: {}
  model_id: ${env.LLAMA3B_MODEL}
  provider_id: llama-3b
  model_type: llm
- metadata: {}
  model_id: ${env.GRANITE_MODEL}
  provider_id: granite 
  model_type: llm
- metadata: {}
  model_id: ${env.SAFETY_MODEL}
  provider_id: vllm-safety
  model_type: llm
- metadata:
    embedding_dimension: 384
  model_id: all-MiniLM-L6-v2
  provider_id: sentence-transformers
  model_type: embedding
shields:
- shield_id: ${env.SAFETY_MODEL}
  provider_id: llama-guard
vector_dbs: []
datasets: []
scoring_fns: []
benchmarks: []
tool_groups:
- toolgroup_id: builtin::websearch
  provider_id: tavily-search
- toolgroup_id: builtin::rag
  provider_id: rag-runtime
- toolgroup_id: builtin::code_interpreter
  provider_id: code-interpreter
```
