### ISSUE TITLE
Set up secrets for build-*-image actions

### ISSUE THREAD

**Issue by booxter** [llamastack/llama-stack-k8s-operator#2]
Actions fail as:

```
Run docker/login-action@v2
  with:
    registry: quay.io
    ecr: auto
    logout: true
Error: Username and password required
```

I believe secrets need to be set up for the repo,

```
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.APP_QUAY_USERNAME }}
          password: ${{ secrets.APP_QUAY_TOKEN }}
```
